INSERT INTO `site` VALUES (1, "localhost", "default", "Default");
INSERT INTO `page` VALUES (1, "Welcome", NOW(), "Home page", FALSE, "home", 0, FALSE, TRUE, 1, NULL, "Home", NOW(), 1);
INSERT INTO `page` VALUES (2, "", NOW(), "Products", FALSE, "products", 1, FALSE, TRUE, 600, NULL, "Products", NOW(), 1);
INSERT INTO `page` VALUES (3, "", NOW(), "About us", FALSE, "aboutus", 1, FALSE, TRUE, 600, NULL, "Aboutus", NOW(), 1);
INSERT INTO `page` VALUES (4, "", NOW(), "Contact us", FALSE, "contactus", 1, FALSE, TRUE, 600, NULL, "Contactus", NOW(), 1);
INSERT INTO `role` VALUES (1,'System administrator','admin'),(2,'Editor','editor'),(3,'User','user');
INSERT INTO `user` VALUES (1,1,NULL,0,'Administrator');
INSERT INTO `userrole` VALUES (1,1);
INSERT INTO `userrole` VALUES (1,2);
INSERT INTO `userrole` VALUES (1,3);
INSERT INTO `credential` SET active=1,authData=SHA1('admin'), authServiceType='password',created=NOW(), email='admin', uid='password:admin', updated=NOW(), userId=1, verified=1;